In [1]:
import pandas as pd

In [2]:
database = pd.read_pickle('databasefromhackernoon.pickle')
headings = pd.read_pickle('headingsfromhackernoon.pickle')
paragraphs = pd.read_pickle('paragraphsfromhackernoon.pickle')

In [3]:
database

,topicheadingID,url,totalsubheadings,totalparagraphs
0,0,https://hackernoon.com/is-blockchain-based-wat...,6,13
1,7,https://hackernoon.com/pros-and-cons-of-develo...,5,26
2,13,https://hackernoon.com/what-is-stabila-coin-an...,1,30
3,15,https://hackernoon.com/doodles-a-brand-exceedi...,5,20
4,21,https://hackernoon.com/self-reliance-is-the-on...,1,12
...,...,...,...,...
7850,51145,https://hackernoon.com/what-is-a-lisk-tree-and...,6,48
7851,51152,https://hackernoon.com/the-ultimate-guide-to-n...,14,32
7852,51167,https://hackernoon.com/tech-giants-and-their-b...,6,23
7853,51174,https://hackernoon.com/parsiq-vs-the-graph-pul...,6,29
7854,51181,https://hackernoon.com/learning-about-financia...,1,28

In [4]:
headings

,tag,headingtext,subheading,nextheading,paragraphs
0,topic,Is Blockchain-Based Watch-to-Earn Monetization...,2,None,[]
1,h3,@ishantechIshanOnTech,None,None,[0]
2,h2,What Is Happening?,None,3,[1]
3,h2,What is Coub.com?,None,4,"[2, 3]"
4,h2,How is Coubâs Web3 Video Space Going to Work?,None,5,"[4, 5, 6, 7]"
...,...,...,...,...,...
51178,h2,The Graph and GraphQL,None,51179,"[251489, 251490, 251491]"
51179,h2,PARSIQ and ParsiQL,None,51180,"[251492, 251493, 251494, 251495]"
51180,h2,Key differences,None,None,"[251496, 251497, 251498, 251499, 251500, 25150..."
51181,topic,Learning About Financial Sovereignty and Priva...,51182,None,[]
51182,h3,@saragpintoSara Pinto,None,None,"[251504, 251505, 251506, 251507, 251508, 25150..."

In [5]:
paragraphs

       tag                                               text
0        p  Covering the latest events, insights and views...
1        p  Coub.com, a micro-video streaming social netwo...
2        p  Coub is a video-sharing website that is access...
3        p  On Coub, users can take any video, trim the be...
4        p  In order to preserve the intrinsic fluidity of...
...     ..                                                ...
251530   p  Thank you for answering our questions adrian a...
251531   p  Thanks Sara Pinto and all! I do realise that A...
251532   p  Anoma is a moonshoot. What we are building is ...
251533   p                Check the socials and website here:
251534   p      Twitter: @anomanetworkWebsite:Â anoma.network

[251535 rows x 2 columns]